#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Recover the real client IP when Dewpoint runs behind a TLS proxy / load balancer.
#
# DEWPOINT_TRUSTED_PROXIES: space- or comma-separated IPs/CIDRs of the proxies in front of this container.
#   Empty (default): X-Forwarded-For from clients is ignored; the TCP peer is the client.
#   Set: nginx walks X-Forwarded-For from the right, skipping trusted hops (real_ip_recursive), so a client
#        can't spoof its address by prepending entries.
# Every entry is validated; an invalid one aborts startup, and the config file is only written once all pass
# (nginx refuses to start without it), so a bad value can never silently trust the wrong peers.
set -eu

out=/tmp/nginx-real-ip.conf
tmp="${out}.new"
proxies=$(printf '%s' "${DEWPOINT_TRUSTED_PROXIES:-}" | tr ',' ' ')

ipv4='^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[12][0-9]|3[0-2]))?$'
ipv6='^[0-9A-Fa-f:]*:[0-9A-Fa-f:.]*(/([0-9]|[1-9][0-9]|1[01][0-9]|12[0-8]))?$'

{
  echo "# generated by 40-dewpoint-real-ip.sh"
  if [ -n "${proxies}" ]; then
    echo "real_ip_header X-Forwarded-For;"
    echo "real_ip_recursive on;"
  fi
} > "${tmp}"

for p in ${proxies}; do
  if printf '%s' "${p}" | grep -Eq "${ipv4}"; then
    for octet in $(printf '%s' "${p%%/*}" | tr '.' ' '); do
      [ "${octet}" -le 255 ] || { echo "dewpoint: invalid DEWPOINT_TRUSTED_PROXIES entry: ${p}" >&2; exit 1; }
    done
  elif ! printf '%s' "${p}" | grep -Eq "${ipv6}"; then
    echo "dewpoint: invalid DEWPOINT_TRUSTED_PROXIES entry: ${p}" >&2
    exit 1
  fi
  echo "set_real_ip_from ${p};" >> "${tmp}"
done

mv "${tmp}" "${out}"
echo "dewpoint: trusted proxies: ${proxies:-none (clients' X-Forwarded-For ignored)}"
